---
title: "Project2"
format: html
editor: visual
execute:
  warning: false
  message: false
  df-print: kable
editor_options: 
  chunk_output_type: console
---

import necessary libraries

```{r}
library(tidyverse)
library(readr)
library(jsonlite)
library(dplyr)
```

load data

```{r}
mobile_device_data <- read_csv("data/user_behavior_dataset.csv") |>
  as_tibble() |>
  rename(
    user_id = `User ID`,
    device_model = `Device Model`,
    operating_system = `Operating System`,
    app_usage_time = `App Usage Time (min/day)`,
    screen_on_time = `Screen On Time (hours/day)`,
    battery_drain = `Battery Drain (mAh/day)`,
    num_app_installed = `Number of Apps Installed`,
    data_usage = `Data Usage (MB/day)`,
    age = Age,
    gender = Gender,
    user_behavior_class = `User Behavior Class`
  )
mobile_device_data
```

```{r}
colnames(mobile_device_data)
```

create factor versions of some variables to use

```{r}
mobile_device_data <- mobile_device_data |>
mutate(across(
c(user_id, device_model, operating_system, gender, user_behavior_class),
as.factor
))

```

create a one way contingency table

```{r}
one_way_table <- mobile_device_data |>
  group_by(gender) |>
  drop_na(gender) |>
  summarize(count = n())
one_way_table
```

create a two way contingency table - comparing which operating system is used more often between males and females

```{r}

two_way_table <- mobile_device_data |>
  group_by(operating_system, gender) |>
  drop_na(operating_system, gender) |>
  summarize(count = n()) |>
  pivot_wider(names_from = gender, values_from = count, values_fill = 0)

two_way_table
```

summarize numerical variables

```{r}
mobile_device_data |>
  summarise(across(
    where(is.numeric),
    list(
      mean = mean,
      sd = sd,
      median = median,
      max = max
    ),
    .names = "{.col}.{.fn}"
  ))
```
